export const productos = [
    {
        id: 1,
        nombre: "Hamburguesa",
        descripcion: "Una deliciosa hamburguesa con carne jugosa, queso derretido, lechuga crujiente, tomate fresco y salsa especial, todo en un suave panecillo.",
        etiqueta: "Burger",
        precio: 9.99,
        imagen: "https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
    },
    {
        id: 2,
        nombre: "Pizza",
        descripcion: "Una pizza recién horneada con una base de salsa de tomate, mozzarella derretida y tus ingredientes favoritos, todo sobre una masa crujiente.",
        etiqueta: "Pizza",
        precio: 12.99,
        imagen: "https://images.pexels.com/photos/1653877/pexels-photo-1653877.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },
    {
        id: 3,
        nombre: "Pollo Frito",
        descripcion: "Trozos de pollo sazonados y empanizados, fritos a la perfección hasta que estén dorados y crujientes por fuera, y jugosos y tiernos por dentro.",
        etiqueta: "Fried Chicken",
        precio: 8.49,
        imagen: "https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },
    {
        id: 4,
        nombre: "Plato Mixto",
        descripcion: "Un plato abundante con una mezcla de sabores deliciosos, que incluye carne asada a la parrilla, pollo a la parrilla, costillas de cerdo ahumadas, papas fritas y verduras asadas.",
        etiqueta: "Mixed Plate",
        precio: 15.99,
        imagen: "https://images.pexels.com/photos/20067063/pexels-photo-20067063/free-photo-of-plato-cena-comida-pez.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },
    {
        id: 5,
        nombre: "Tacos",
        descripcion: "Tortillas de maíz rellenas de carne sazonada, cebolla picada, cilantro fresco, y acompañadas de salsa picante, limón y guarniciones frescas como aguacate y rábanos.",
        etiqueta: "Tacos",
        precio: 10.99,
        imagen: "https://images.pexels.com/photos/4958641/pexels-photo-4958641.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },
    {
        id: 6,
        nombre: "Sushi",
        descripcion: "Rodajas de pescado fresco, arroz de sushi perfectamente cocido, alga nori y una variedad de ingredientes frescos y sabrosos, todo enrollado en una exquisita pieza de sushi.",
        etiqueta: "Sushi",
        precio: 18.99,
        imagen: "https://images.pexels.com/photos/2098085/pexels-photo-2098085.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },
];